name = "ModelingToolkitCourse"
uuid = "d0ecabdd-fe99-481e-9814-e16fa9c541df"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]
version = "1.0.0"

[deps]
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"

[compat]
ModelingToolkit = "9"

[extras]
ExplicitImports = "7d51a73a-1435-4ff3-83d9-f097790105c7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ExplicitImports", "Test"]
